name: Java_CI_with_Gradle

on:
  push:
    branches: ["main" , "feature/add-upgrade"]
  pull_request:
    branches: ["main"]

jobs:

  test_job:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref }} 
      TAG: ${{ github.sha }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Run tests with Gradle
      run: ./gradlew test --continue

  build_job:
    runs-on: ubuntu-latest
    needs: test_job
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-


    - name: Grant execute permission to Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

    - name: Show variables
      run: echo "This is my variable $REPO_NAME"
      env:
        REPO_NAME: ${{ vars.REPO_NAME }}
    

    - name: Debug Check build output
      working-directory: build/libs
      run: ls -la
    

    - name: Rename JAR for Docker
      run: mv build/libs/*.jar build/libs/app.jar

    - name: Verify JAR before Docker
      run: ls -la build/libs/app.jar

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ vars.REPO_NAME }}:V-${{ env.BRANCH_NAME }}-${{ env.TAG }}