name: Java_CI_with_Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle Wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

    - name: Debug Check build output
      run: ls -la build/libs/

    - name: Rename JAR for Docker
      run: |
        ls -la build/libs/
        JAR_FILE=$(ls build/libs/*.jar | head -n 1)
        mv "$JAR_FILE" build/libs/app.jar

    - name: Verify JAR before Docker
      run: ls -la build/libs/app.jar

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: egorravino/demo-image-java-app:v1-main-${{ github.sha }}
