name: Java_CI_with_Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Check Java version
      run: java -version

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Gradle execute permission 
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Debug List build artifacts
      run: ls -la build/libs/

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: egorravino/demo-image-java-app
        tag: v1-main-${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: .
